### ISSUE TITLE
Error in bin/custom

### ISSUE THREAD

**Issue by dryabov** [webpro/DOMtastic#30]
bin/custom triggers following error on my side:
```
DOMtastic\node_modules\browserify\node_modules\resolve\lib\sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
          ^
Error: Cannot find module 'bundle-collapser/plugin' from 'src'
    at Function.module.exports [as sync] (DOMtastic\node_modules\browserify\node_modules\resolve\lib\sync.js:33:11)
    at Browserify.plugin (DOMtastic\node_modules\browserify\index.js:342:29)
    at bundle (DOMtastic\bin\custom:59:10)
    at DOMtastic\bin\custom:83:9
    at f (DOMtastic\node_modules\glob\node_modules\once\once.js:17:25)
    at Glob.<anonymous> (DOMtastic\node_modules\glob\glob.js:132:7)
    at Glob.EventEmitter.emit (events.js:95:17)
    at Glob._finish (DOMtastic\node_modules\glob\glob.js:171:8)
    at done (DOMtastic\node_modules\glob\glob.js:158:12)
    at Glob._processGlobStar2 (DOMtastic\node_modules\glob\glob.js:589:12)
```
I had to patch part of bin/custom to be
```
        .transform(require('redirectify'), redirectifyOptions)
        .transform(require('babelify'))
        .transform(require('browserify-versionify'), {
            placeholder: '__VERSION__',
            version: pkg.version
        })
        .plugin(require('bundle-collapser/plugin'))
```
to build it correctly.

PS. I built DOMTastic on Windows, maybe it's the reason of modules are not required automatically.

**Comment by webpro** [comment]
@dryabov OK, I've pushed a fix in a separate branch. If you confirm this works for you I can merge/release it.

Thanks for the catch (although I couldn't find other Browserify issues from other Windows users). Are you sure your `node_modules` folder was up-to-date etc.?

**Comment by dryabov** [comment]
It was the first thing I tested, and removing node_modules doesn't fix the issue.

issue-30 branch should work because of it is exactly the code I've run successfully.

**Comment by webpro** [comment]
Thanks @dryabov, just released v0.10.3.
